# Generated by Django 5.2.10 on 2026-01-15 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Template title', max_length=255)),
                ('content', models.TextField(help_text='Template content with {{VARIABLE_NAME}} or [VARIABLE_NAME] placeholders')),
                ('agent_role', models.CharField(choices=[('orchestrator', 'Orchestrator'), ('analyst', 'Analyst'), ('pm', 'Project Manager'), ('architect', 'Architect'), ('scrum_master', 'Scrum Master'), ('developer', 'Developer'), ('qa', 'QA Engineer')], help_text='BMAD agent role associated with this template', max_length=50)),
                ('workflow_phase', models.CharField(choices=[('planning', 'Planning Phase'), ('development', 'Development Phase')], help_text='BMAD workflow phase associated with this template', max_length=50)),
                ('remote_url', models.URLField(blank=True, help_text='Original remote URL where this template was synced from', max_length=500, null=True)),
                ('remote_path', models.CharField(blank=True, help_text='File path in the remote repository', max_length=500, null=True)),
                ('description', models.TextField(blank=True, help_text='Template description and usage instructions', null=True)),
                ('version', models.CharField(default='1.0.0', help_text='Template version', max_length=50)),
                ('variables', models.JSONField(blank=True, default=list, help_text='Detected variables in the template')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active and available for use')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time this template was updated')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this template was first created')),
            ],
            options={
                'ordering': ['agent_role', 'workflow_phase', 'title'],
                'indexes': [models.Index(fields=['agent_role', 'workflow_phase'], name='forge_templ_agent_r_f779fb_idx'), models.Index(fields=['is_active', 'created_at'], name='forge_templ_is_acti_1ca3dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='GeneratedPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField(help_text='User input data used to generate the prompt')),
                ('final_output', models.TextField(help_text='The generated prompt output')),
                ('is_valid', models.BooleanField(default=False, help_text='Whether the generated prompt is BMAD-compliant')),
                ('validation_notes', models.JSONField(blank=True, default=list, help_text='Notes from BMAD validation checks')),
                ('missing_variables', models.JSONField(blank=True, default=list, help_text='List of variables that were not replaced')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this prompt was generated')),
                ('template', models.ForeignKey(help_text='The template used to generate this prompt', on_delete=django.db.models.deletion.CASCADE, related_name='generated_prompts', to='forge.template')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['template', 'created_at'], name='forge_gener_templat_822228_idx'), models.Index(fields=['is_valid', 'created_at'], name='forge_gener_is_vali_598504_idx')],
            },
        ),
    ]
