# Generated by Django 5.2.10 on 2026-01-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='agent_roles',
            field=models.JSONField(blank=True, default=list, help_text='List of all BMAD agent roles that can use this template'),
        ),
        migrations.AlterField(
            model_name='template',
            name='agent_role',
            field=models.CharField(choices=[('orchestrator', 'Orchestrator'), ('analyst', 'Analyst'), ('pm', 'Project Manager'), ('architect', 'Architect'), ('scrum_master', 'Scrum Master'), ('developer', 'Developer'), ('qa', 'QA Engineer')], help_text='Primary BMAD agent role associated with this template', max_length=50),
        ),
    ]
